// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4xqRKjEIiDLLt7wmpaiqSu82NhbxzFvo',
    appId: '1:739776757569:web:21ed2af5aaf6c69c8b2bc0',
    messagingSenderId: '739776757569',
    projectId: 'cynix-826d1',
    authDomain: 'cynix-826d1.firebaseapp.com',
    storageBucket: 'cynix-826d1.firebasestorage.app',
    measurementId: 'G-6KXTGLZ1JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIXVGJxlvzJ0c5F8EBG7U93lvQGUj_c7Y',
    appId: '1:739776757569:android:2b1a86c87dca5b2f8b2bc0',
    messagingSenderId: '739776757569',
    projectId: 'cynix-826d1',
    storageBucket: 'cynix-826d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBFgP5ytNXp3jm9NrqrUyuitJc8-_w94w',
    appId: '1:739776757569:ios:e515f020fd70e3c38b2bc0',
    messagingSenderId: '739776757569',
    projectId: 'cynix-826d1',
    storageBucket: 'cynix-826d1.firebasestorage.app',
    iosBundleId: 'com.example.cynix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBFgP5ytNXp3jm9NrqrUyuitJc8-_w94w',
    appId: '1:739776757569:ios:e515f020fd70e3c38b2bc0',
    messagingSenderId: '739776757569',
    projectId: 'cynix-826d1',
    storageBucket: 'cynix-826d1.firebasestorage.app',
    iosBundleId: 'com.example.cynix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4xqRKjEIiDLLt7wmpaiqSu82NhbxzFvo',
    appId: '1:739776757569:web:9319995c30dae9908b2bc0',
    messagingSenderId: '739776757569',
    projectId: 'cynix-826d1',
    authDomain: 'cynix-826d1.firebaseapp.com',
    storageBucket: 'cynix-826d1.firebasestorage.app',
    measurementId: 'G-HZE5K52EXX',
  );
}
